### ISSUE TITLE
Cannot find module init.js

### ISSUE THREAD

**Issue by probonopd** [EHDFE/ehdev-shell#363]
```
module.js:545
    throw err;
    ^
Error: Cannot find module '/run/firejail/appimage/.appimage-7052/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

References:
* https://travis-ci.org/AppImage/appimage.github.io/builds/386042988#L625-L634
* https://github.com/AppImage/appimage.github.io/pull/575

**Comment by probonopd** [comment]
Please ping me once a release containing this fix is available so that I can add it to the AppImageHub directory of available AppImages.
